const SESSION_TAG = 'SESSION_TAG'
const WISHLIST_TAG = 'WISHLIST_TAG'
const CART_TAG = 'CART_TAG'
const RESEARCH_LIST_TAG = 'RESEARCH_LIST'
const RESEARCH_ITEM_TAG = 'RESEARCH_ITEM'

export {
  RESEARCH_LIST_TAG,
  RESEARCH_ITEM_TAG,
  CART_TAG,
  WISHLIST_TAG,
  SESSION_TAG,
}
